matrix:
  include:
    # 1. run the Test for Readability, Maintainability and Functionality Errors
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint && cd ../demo-angular && npm run ci.tslint

    #WebPack and Build Demo Apps with Your Plugin Installed
    - stage: "WebPack"
    #  os: osx
    #  env:
    #    - Platform="iOS"
    #  osx_image: xcode8.3
    #  language: node_js
    #  node_js: "6"
    #  jdk: oraclejdk8
    #  script: cd demo && npm run build.plugin && npm i && npm run build-ios-bundle && cd ../demo-angular && npm run build.plugin && npm i && npm run build-ios-bundle
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd demo && npm run build.plugin && npm i && npm run build-android-bundle && cd ../demo-angular && npm run build.plugin && npm i && npm run build-android-bundle
    - stage: "Build"
      env:
        - Android="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd demo && npm run ci.android.build && cd ../demo-angular && npm run ci.android.build
    #- os: osx
    #  env:
    #    - iOS="10.3"
    #    - Xcode="8.3"
    #  osx_image: xcode8.3
    #  language: node_js
    #  node_js: "6"
    #  #jdk: oraclejdk8
    #  script: cd demo && npm run ci.ios.build && cd ../demo-angular && npm run ci.ios.build

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable